sudo: required
language: bash
services:
- docker
before_install:
- docker build -t jinwuzhao/emacs-web .
deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
env:
  global:
  - secure: pvtY0M0LE0E5jqqASWtDt4JDLp4x46mzqz3Dt8N689FKcSRwUvH82NBufkjADfWFLimi8S9Q7QTDKFbqXv+CFP7I8FH6SQqegve8Nl2i1Ye92/ttJmU943w5JRqr4d5HOkiAWhRUCppQx83YtOaNEAVeJ5BJ+SoCs4SxTt4BDnrb8sPYp8pRcxOgi3bCLuvRSL3D9z4jGHZ0CFGY27s6tFgxXIwL/mrwwtyFhUCLYKHZ9KYM6ZAPyJXmqfbVXPjufKSCG7W4/y31e8PNUGrq2+B3s1Ox8jVGZ7CVEbpz/Rtaz0i9EGowPrZGJEYfKS/uTxRZwsGZJpr9nVH8DOkDknTFLRm024uuls0LNxJthArNmuvUwSmHHJlk68MoW9vRJtjxe4C+83pZaIIJML892F0HlX9VaTRM/KnjYTRJIIhg7Q8qSt2mGzJXWWj3EZFM1pqtHIkwBXpoe0I6e0UrN/EfCYCD8iDqU2NLteqjiCqyYRF5TC86FPsLWJ0v3q5tg0o2yrHGTEI6VIG3ssov4Sltzcq6Se1kGN/VMH9nmCCEEYK1WwxXKdLBfPOTVtYtboU+N7+lK27J0vROR+PWWyuIfphRakbxEYvkSPxhtL3/QIWO5i90WMIuyKmeQDOS1BbNxBpGux6/OonzVOeQQnFni8LNz47DB05z+3fpSbs=
  - secure: BkZ0vUgc5WvCI3RJh6cXytdb3DUGfGdBtf+hDDATBWp2pYP4pe0BnXTpkevZXa7SyHSwRBp5w39sHAkly0jx5gAY49+VOes/ZfJBTeqSap+hWoIDZwIY7aJdKzrBQriBK1hKRTIkAOdd97+T1yDWtPF4kWok9fFrdNhPwFmSk3ioiqqYoSCxOWRlQ3e/RcO+5r2Ofuq9OM6Bd8yG3dUD/O8mGUnNhjiEUs0kxyLjN+uvDOyI/nvOhyCu9ji0xzmnWzQACc+wZIaRxUUAWOp4uWVtDpgPKFO7TTRjZC358So5WKzlVBJenzrmbEgBOKS+yl0YZlm5/xWDvw/+1uvtOnM7WtSSjt2r5SfMYA7OYt0JlZM9xBmWoNfI6tUnsaoxU9GQD0tGeefISVwzSaN0Ee6u0OYFs+CWT1oUy8BapyCI2GDhYWYu0ZFszS4q7OsDyX3lM1fFXMlmxwNx/VXCEQZkFIeNIqlmnZpr0gdqG31aPV4eeYGiSqCcTF4vVqNGXLH3yrbKURG63B1QB3jhpLRmotoGrK8HFQVKVakF5eXph/utuZlv3ONK7BLVsE6BKJp4DjcHCWCg2J/aVD9ZnLzifwPtg31K2n6ac/C+D6grv8T8VcTpKJEGSnHozDb58Gf49x8+xpJEY2Exl7hAt4mmN1lFTqd5s52QuuZ2TC8=
