#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push jinwuzhao/emacs-web
docker tag jinwuzhao/emacs-web jinwuzhao/emacs-web:$TRAVIS_TAG
docker push jinwuzhao/emacs-web:$TRAVIS_TAG
docker logout
